#!/usr/bin/env python

import argparse
import json
import yaml
import jmespath

DESCRIPTION = """
jmespath query tool for JSON and YAML files.

jmespath provides XPath like filters to query JSON data.
"""

ap = argparse.ArgumentParser(description=DESCRIPTION)
ap.add_argument('JSONPATH', help='jmespath expression')
ap.add_argument('FILES', nargs='+', help='JSON or YAML files')

if __name__ == '__main__':
    args = ap.parse_args()

    jpexpr = jmespath.compile(args.JSONPATH)

    for j in args.FILES:
        with open(j, 'r') as f:
            J = None 

            try:
                J = json.load(f)
            except ValueError, e:
                f.seek(0)    
                try:
                    J = yaml.load(f)
                except:
                    raise
            print(json.dumps(jpexpr.search(J), indent=2))

# vim: sts=4 ts=4 sw=4 et:
